export const INDUSTRIES = [
  "Technology & SaaS",
  "Software Engineering & DevOps",
  "Data Science & Artificial Intelligence",
  "Financial Services, Banking & Fintech",
  "Investment Banking & Venture Capital",
  "Healthcare, Pharma & Biotech",
  "Professional & Management Consulting",
  "Legal Services",
  "Energy, Oil, Gas & Utilities",
  "Renewable Energy & Cleantech",
  "Consumer Goods, Retail & E-commerce",
  "Manufacturing, Industrial & Robotics",
  "Aerospace & Defense",
  "Automotive & Autonomous Systems",
  "Real Estate, Proptech & Construction",
  "Media, Entertainment & Gaming",
  "Telecommunications & 5G/6G Networks",
  "Marketing & Public Relations",
  "Education & Edtech",
  "Non-Profit, NGO & Public Sector",
  "Logistics, Supply Chain & Maritime",
  "Agriculture, Foodtech & Forestry",
  "Hospitality, Travel & Leisure",
  "Chemicals & Materials",
  "Environmental & Sustainability Services"
];

export const COUNTRIES_AND_CITIES: Record<string, string[]> = {
  "Afghanistan": ["Kabul", "Herat", "Mazar-i-Sharif", "Kandahar", "Jalalabad"],
  "Albania": ["Tirana", "Durres", "Vlore", "Shkoder", "Elbasan"],
  "Algeria": ["Algiers", "Oran", "Constantine", "Annaba", "Batna"],
  "Andorra": ["Andorra la Vella", "Escaldes-Engordany", "Encamp"],
  "Angola": ["Luanda", "Lubango", "Huambo", "Benguela", "Lobito"],
  "Antigua and Barbuda": ["St. John's", "All Saints", "Liberta"],
  "Argentina": ["Buenos Aires", "Cordoba", "Rosario", "Mendoza", "San Miguel de Tucuman", "La Plata"],
  "Armenia": ["Yerevan", "Gyumri", "Vanadzor", "Vagharshapat"],
  "Australia": ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Canberra", "Hobart", "Gold Coast"],
  "Austria": ["Vienna", "Salzburg", "Graz", "Linz", "Innsbruck", "Klagenfurt"],
  "Azerbaijan": ["Baku", "Ganja", "Sumqayit", "Lankaran"],
  "Bahamas": ["Nassau", "Freeport", "West End"],
  "Bahrain": ["Manama", "Riffa", "Muharraq", "Hamad Town"],
  "Bangladesh": ["Dhaka", "Chittagong", "Khulna", "Sylhet", "Rajshahi"],
  "Barbados": ["Bridgetown", "Speightstown", "Oistins"],
  "Belarus": ["Minsk", "Gomel", "Mogilev", "Vitebsk", "Grodno"],
  "Belgium": ["Brussels", "Antwerp", "Ghent", "Bruges", "Liege", "Leuven"],
  "Belize": ["Belmopan", "Belize City", "San Ignacio"],
  "Benin": ["Porto-Novo", "Cotonou", "Parakou"],
  "Bhutan": ["Thimphu", "Phuntsholing", "Paro"],
  "Bolivia": ["La Paz", "Sucre", "Santa Cruz de la Sierra", "Cochabamba", "El Alto"],
  "Bosnia and Herzegovina": ["Sarajevo", "Banja Luka", "Mostar", "Tuzla"],
  "Botswana": ["Gaborone", "Francistown", "Molepolole"],
  "Brazil": ["Sao Paulo", "Rio de Janeiro", "Brasilia", "Salvador", "Belo Horizonte", "Fortaleza", "Curitiba"],
  "Brunei": ["Bandar Seri Begawan", "Kuala Belait", "Seria"],
  "Bulgaria": ["Sofia", "Plovdiv", "Varna", "Burgas", "Ruse"],
  "Burkina Faso": ["Ouagadougou", "Bobo-Dioulasso", "Koudougou"],
  "Burundi": ["Gitega", "Bujumbura", "Muyinga"],
  "Cabo Verde": ["Praia", "Mindelo", "Santa Maria"],
  "Cambodia": ["Phnom Penh", "Siem Reap", "Battambang", "Sihanoukville"],
  "Cameroon": ["Yaounde", "Douala", "Garoua", "Bamenda"],
  "Canada": ["Toronto", "Vancouver", "Montreal", "Calgary", "Ottawa", "Edmonton", "Quebec City", "Halifax", "Winnipeg"],
  "Central African Republic": ["Bangui", "Bimbo", "Mbaiki"],
  "Chad": ["N'Djamena", "Moundou", "Sarh"],
  "Chile": ["Santiago", "Valparaiso", "Concepcion", "Vina del Mar", "Antofagasta"],
  "China": ["Beijing", "Shanghai", "Shenzhen", "Guangzhou", "Hangzhou", "Chengdu", "Wuhan", "Nanjing"],
  "Colombia": ["Bogota", "Medellin", "Cali", "Barranquilla", "Cartagena"],
  "Comoros": ["Moroni", "Mutsamudu", "Fomboni"],
  "Congo (Congo-Brazzaville)": ["Brazzaville", "Pointe-Noire", "Dolisie"],
  "Costa Rica": ["San Jose", "Alajuela", "Cartago", "Heredia"],
  "Croatia": ["Zagreb", "Split", "Rijeka", "Osijek"],
  "Cuba": ["Havana", "Santiago de Cuba", "Camaguey", "Holguin"],
  "Cyprus": ["Nicosia", "Limassol", "Larnaca", "Paphos"],
  "Czech Republic": ["Prague", "Brno", "Ostrava", "Plzen"],
  "Denmark": ["Copenhagen", "Aarhus", "Odense", "Aalborg"],
  "Djibouti": ["Djibouti City", "Ali Sabieh", "Tadjoura"],
  "Dominica": ["Roseau", "Portsmouth"],
  "Dominican Republic": ["Santo Domingo", "Santiago de los Caballeros", "La Romana"],
  "East Timor": ["Dili", "Baucau", "Liquica"],
  "Ecuador": ["Quito", "Guayaquil", "Cuenca", "Santo Domingo"],
  "Egypt": ["Cairo", "Alexandria", "Giza", "Shubra El-Kheima", "Port Said"],
  "El Salvador": ["San Salvador", "Santa Ana", "San Miguel"],
  "Equatorial Guinea": ["Malabo", "Bata", "Enebiyan"],
  "Eritrea": ["Asmara", "Keren", "Massawa"],
  "Estonia": ["Tallinn", "Tartu", "Narva", "Parnu"],
  "Eswatini": ["Mbabane", "Manzini", "Lobamba"],
  "Ethiopia": ["Addis Ababa", "Dire Dawa", "Adama", "Gondar"],
  "Fiji": ["Suva", "Lautoka", "Nadi"],
  "Finland": ["Helsinki", "Espoo", "Tampere", "Vantaa", "Turku", "Oulu"],
  "France": ["Paris", "Lyon", "Marseille", "Toulouse", "Nice", "Nantes", "Strasbourg", "Bordeaux", "Lille"],
  "Gabon": ["Libreville", "Port-Gentil", "Franceville"],
  "Gambia": ["Banjul", "Serekunda", "Brikama"],
  "Georgia": ["Tbilisi", "Batumi", "Kutaisi", "Rustavi"],
  "Germany": ["Berlin", "Munich", "Frankfurt", "Hamburg", "Cologne", "Stuttgart", "Dusseldorf", "Leipzig"],
  "Ghana": ["Accra", "Kumasi", "Tamale", "Takoradi"],
  "Greece": ["Athens", "Thessaloniki", "Patras", "Piraeus", "Heraklion"],
  "Grenada": ["St. George's", "Gouyave", "Grenville"],
  "Guatemala": ["Guatemala City", "Mixco", "Villa Nueva", "Quetzaltenango"],
  "Guinea": ["Conakry", "Nzerekore", "Kankan", "Kindia"],
  "Guinea-Bissau": ["Bissau", "Bafata", "Gabú"],
  "Guyana": ["Georgetown", "Linden", "New Amsterdam"],
  "Haiti": ["Port-au-Prince", "Carrefour", "Delmas", "Cap-Haitien"],
  "Honduras": ["Tegucigalpa", "San Pedro Sula", "Choloma", "La Ceiba"],
  "Hungary": ["Budapest", "Debrecen", "Szeged", "Miskolc", "Pecs"],
  "Iceland": ["Reykjavik", "Kopavogur", "Hafnarfjordur", "Akureyri"],
  "India": ["Mumbai", "Bangalore (Bengaluru)", "New Delhi", "Pune", "Hyderabad", "Chennai", "Kolkata", "Ahmedabad", "Gurugram", "Noida"],
  "Indonesia": ["Jakarta", "Surabaya", "Bandung", "Medan", "Bekasi", "Tangerang", "Bali (Denpasar)"],
  "Iran": ["Tehran", "Mashhad", "Isfahan", "Karaj", "Tabriz"],
  "Iraq": ["Baghdad", "Basra", "Mosul", "Erbil", "Sulaymaniyah"],
  "Ireland": ["Dublin", "Cork", "Limerick", "Galway", "Waterford"],
  "Israel": ["Tel Aviv", "Jerusalem", "Haifa", "Rishon LeZion", "Petah Tikva"],
  "Italy": ["Rome", "Milan", "Naples", "Turin", "Palermo", "Genoa", "Florence", "Bologna", "Venice"],
  "Ivory Coast": ["Yamoussoukro", "Abidjan", "Bouake", "Daloa"],
  "Jamaica": ["Kingston", "Spanish Town", "Portmore", "Montego Bay"],
  "Japan": ["Tokyo", "Osaka", "Kyoto", "Yokohama", "Nagoya", "Fukuoka", "Sapporo", "Kobe"],
  "Jordan": ["Amman", "Zarqa", "Irbid", "Aqaba"],
  "Kazakhstan": ["Astana", "Almaty", "Shymkent", "Karaganda"],
  "Kenya": ["Nairobi", "Mombasa", "Kisumu", "Nakuru"],
  "Kiribati": ["Tarawa", "Betio", "Bikenibeu"],
  "Kuwait": ["Kuwait City", "Al Ahmadi", "Hawalli", "Salmiya"],
  "Kyrgyzstan": ["Bishkek", "Osh", "Jalal-Abad"],
  "Laos": ["Vientiane", "Luang Prabang", "Savannakhet", "Pakse"],
  "Latvia": ["Riga", "Daugavpils", "Liepaja", "Jelgava"],
  "Lebanon": ["Beirut", "Tripoli", "Sidon", "Tyre", "Byblos"],
  "Lesotho": ["Maseru", "Teyateyaneng", "Mafeteng"],
  "Liberia": ["Monrovia", "Gbarnga", "Kakata"],
  "Libya": ["Tripoli", "Benghazi", "Misrata", "Tarhuna"],
  "Liechtenstein": ["Vaduz", "Schaan", "Triesen"],
  "Lithuania": ["Vilnius", "Kaunas", "Klaipeda", "Siauliai"],
  "Luxembourg": ["Luxembourg City", "Esch-sur-Alzette", "Differdange"],
  "Madagascar": ["Antananarivo", "Toamasina", "Antsirabe", "Mahajanga"],
  "Malawi": ["Lilongwe", "Blantyre", "Mzuzu", "Zomba"],
  "Malaysia": ["Kuala Lumpur", "George Town (Penang)", "Johor Bahru", "Kota Kinabalu", "Kuching", "Ipoh"],
  "Maldives": ["Male", "Hulhumale", "Addu City"],
  "Mali": ["Bamako", "Sikasso", "Mopti", "Kayes"],
  "Malta": ["Valletta", "Birkirkara", "Mosta", "Sliema"],
  "Marshall Islands": ["Majuro", "Ebeye"],
  "Mauritania": ["Nouakchott", "Nouadhibou", "Néma"],
  "Mauritius": ["Port Louis", "Beau Bassin-Rose Hill", "Vacoas-Phoenix", "Curepipe"],
  "Mexico": ["Mexico City", "Guadalajara", "Monterrey", "Puebla", "Tijuana", "Cancun", "Chihuahua"],
  "Micronesia": ["Palikir", "Weno", "Kolonia"],
  "Moldova": ["Chisinau", "Balti", "Tiraspol"],
  "Monaco": ["Monaco-Ville", "Monte Carlo", "La Condamine"],
  "Mongolia": ["Ulaanbaatar", "Erdenet", "Darkhan"],
  "Montenegro": ["Podgorica", "Niksic", "Pljevlja"],
  "Morocco": ["Rabat", "Casablanca", "Marrakesh", "Fes", "Tangier", "Agadir"],
  "Mozambique": ["Maputo", "Matola", "Beira", "Nampula"],
  "Myanmar": ["Naypyidaw", "Yangon", "Mandalay", "Mawlamyine"],
  "Namibia": ["Windhoek", "Walvis Bay", "Swakopmund"],
  "Nauru": ["Yaren", "Denigomodu"],
  "Nepal": ["Kathmandu", "Pokhara", "Lalitpur", "Biratnagar"],
  "Netherlands": ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven", "Groningen"],
  "New Zealand": ["Auckland", "Wellington", "Christchurch", "Hamilton", "Dunedin", "Tauranga"],
  "Nicaragua": ["Managua", "Leon", "Masaya", "Granada"],
  "Niger": ["Niamey", "Zinder", "Maradi"],
  "Nigeria": ["Lagos", "Abuja", "Ibadan", "Kano", "Port Harcourt", "Benin City"],
  "North Korea": ["Pyongyang", "Hamhung", "Chongjin", "Nampo"],
  "North Macedonia": ["Skopje", "Bitola", "Kumanovo", "Ohrid"],
  "Norway": ["Oslo", "Bergen", "Trondheim", "Stavanger", "Sandnes", "Tromso"],
  "Oman": ["Muscat", "Salalah", "Seeb", "Sohar", "Nizwa"],
  "Pakistan": ["Karachi", "Lahore", "Islamabad", "Faisalabad", "Rawalpindi", "Peshawar"],
  "Palau": ["Ngerulmud", "Koror", "Meyuns"],
  "Panama": ["Panama City", "Colon", "David", "Chitre"],
  "Papua New Guinea": ["Port Moresby", "Lae", "Mount Hagen"],
  "Paraguay": ["Asuncion", "Ciudad del Este", "San Lorenzo", "Luque"],
  "Peru": ["Lima", "Arequipa", "Trujillo", "Chiclayo", "Iquitos"],
  "Philippines": ["Manila", "Quezon City", "Davao City", "Cebu City", "Cagayan de Oro", "Makati"],
  "Poland": ["Warsaw", "Krakow", "Wroclaw", "Poznan", "Gdansk", "Katowice"],
  "Portugal": ["Lisbon", "Porto", "Braga", "Coimbra", "Funchal", "Faro"],
  "Qatar": ["Doha", "Al Rayyan", "Al Wakrah", "Al Khor", "Umm Salal Mohammad"],
  "Romania": ["Bucharest", "Cluj-Napoca", "Timișoara", "Iași", "Constanța", "Brașov"],
  "Russia": ["Moscow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg", "Nizhny Novgorod", "Kazan"],
  "Rwanda": ["Kigali", "Butare", "Gisenyi", "Ruhengeri"],
  "Saint Kitts and Nevis": ["Basseterre", "Charlestown"],
  "Saint Lucia": ["Castries", "Gros Islet", "Vieux Fort"],
  "Saint Vincent and the Grenadines": ["Kingstown"],
  "Samoa": ["Apia"],
  "San Marino": ["City of San Marino", "Serravalle", "Borgo Maggiore"],
  "Sao Tome and Principe": ["São Tomé", "Trindade"],
  "Saudi Arabia": ["Riyadh", "Jeddah", "Dammam", "Khobar", "Mecca", "Medina", "Dhahran", "Jubail"],
  "Senegal": ["Dakar", "Thies", "Kaolack", "Ziguinchor"],
  "Serbia": ["Belgrade", "Novi Sad", "Nis", "Kragujevac"],
  "Seychelles": ["Victoria", "Anse Boileau"],
  "Sierra Leone": ["Freetown", "Bo", "Kenema"],
  "Singapore": ["Singapore", "Changi", "Jurong", "Woodlands", "Bedok", "Sengkang"],
  "Slovakia": ["Bratislava", "Kosice", "Presov", "Zilina"],
  "Slovenia": ["Ljubljana", "Maribor", "Celje", "Kranj"],
  "Solomon Islands": ["Honiara"],
  "Somalia": ["Mogadishu", "Hargeisa", "Garowe", "Kismayo"],
  "South Africa": ["Johannesburg", "Cape Town", "Durban", "Pretoria", "Port Elizabeth (Gqeberha)"],
  "South Korea": ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon", "Gwangju"],
  "South Sudan": ["Juba", "Wau", "Malakal"],
  "Spain": ["Madrid", "Barcelona", "Valencia", "Seville", "Zaragoza", "Malaga", "Bilbao"],
  "Sri Lanka": ["Colombo", "Kandy", "Galle", "Jaffna", "Negombo"],
  "Sudan": ["Khartoum", "Omdurman", "Port Sudan"],
  "Suriname": ["Paramaribo", "Lelydorp"],
  "Sweden": ["Stockholm", "Gothenburg", "Malmo", "Uppsala", "Vasteras", "Linkoping"],
  "Switzerland": ["Zurich", "Geneva", "Basel", "Bern", "Lausanne", "Lucerne", "Lugano"],
  "Syria": ["Damascus", "Aleppo", "Homs", "Latakia"],
  "Taiwan": ["Taipei", "Hsinchu", "Kaohsiung", "Taichung", "Tainan", "Taoyuan"],
  "Tajikistan": ["Dushanbe", "Khujand", "Kulob"],
  "Tanzania": ["Dodoma", "Dar es Salaam", "Arusha", "Mwanza", "Zanzibar City"],
  "Thailand": ["Bangkok", "Nonthaburi", "Chiang Mai", "Phuket", "Pattaya", "Hat Yai"],
  "Togo": ["Lomé", "Sokodé", "Kara"],
  "Tonga": ["Nuku'alofa"],
  "Trinidad and Tobago": ["Port of Spain", "Chaguanas", "San Fernando"],
  "Tunisia": ["Tunis", "Sfax", "Sousse", "Kairouan"],
  "Turkey": ["Istanbul", "Ankara", "Izmir", "Bursa", "Antalya", "Adana", "Gaziantep"],
  "Turkmenistan": ["Ashgabat", "Turkmenbashi", "Mary"],
  "Tuvalu": ["Funafuti"],
  "Uganda": ["Kampala", "Entebbe", "Gulu", "Mbarara", "Jinja"],
  "Ukraine": ["Kyiv", "Kharkiv", "Odesa", "Dnipro", "Lviv", "Zaporizhzhia"],
  "United Arab Emirates": ["Dubai", "Abu Dhabi", "Sharjah", "Ajman", "Ras Al Khaimah", "Fujairah", "Umm Al Quwain", "Al Ain"],
  "United Kingdom": ["London", "Manchester", "Birmingham", "Edinburgh", "Glasgow", "Leeds", "Bristol", "Belfast", "Newcastle", "Cambridge", "Oxford"],
  "United States": ["New York City, NY", "San Francisco, CA", "Silicon Valley, CA", "Seattle, WA", "Austin, TX", "Chicago, IL", "Los Angeles, CA", "Boston, MA", "Denver, CO", "Atlanta, GA", "Miami, FL", "Washington, DC"],
  "Uruguay": ["Montevideo", "Saldo", "Paysandu"],
  "Uzbekistan": ["Tashkent", "Samarkand", "Namangan", "Andijan"],
  "Vanuatu": ["Port Vila", "Luganville"],
  "Vatican City": ["Vatican City"],
  "Venezuela": ["Caracas", "Maracaibo", "Valencia", "Barquisimeto", "Maracay"],
  "Vietnam": ["Ho Chi Minh City", "Hanoi", "Da Nang", "Hai Phong", "Can Tho"],
  "Yemen": ["Sanaa", "Aden", "Taiz", "Al Hudaydah"],
  "Zambia": ["Lusaka", "Kitwe", "Ndola", "Kabwe"],
  "Zimbabwe": ["Harare", "Bulawayo", "Chitungwiza", "Mutare"]
};

export const DEPARTMENTS_AND_TITLES: Record<string, string[]> = {
  "Engineering & Technology": [
    "Software Engineer",
    "Senior Software Engineer",
    "Lead Software Engineer",
    "Staff Software Engineer",
    "Engineering Manager",
    "Director of Engineering",
    "VP of Engineering",
    "Chief Technology Officer (CTO)",
    "DevOps Engineer",
    "Cloud Architect",
    "Frontend Developer",
    "Backend Developer",
    "Fullstack Developer",
    "QA Automation Engineer",
    "Solutions Architect",
    "Reliability Engineer (SRE)",
    "Systems Engineer",
    "Firmware Engineer",
    "Mobile App Developer (iOS/Android)",
    "Technical Program Manager (TPM)"
  ],
  "Data Science, Analytics & AI": [
    "Data Scientist",
    "Senior Data Scientist",
    "Machine Learning Engineer",
    "AI Researcher",
    "NLP Specialist",
    "Computer Vision Engineer",
    "Data Analyst",
    "Data Engineer",
    "Senior Data Engineer",
    "Director of AI/ML",
    "BI Analyst (Business Intelligence)",
    "Analytics Manager",
    "Database Administrator (DBA)",
    "MLOps Engineer"
  ],
  "Product, UI/UX & Design": [
    "Associate Product Manager",
    "Product Manager",
    "Senior Product Manager",
    "Director of Product",
    "VP of Product",
    "Product Owner",
    "UI/UX Designer",
    "Senior Product Designer",
    "UX Researcher",
    "Design Manager",
    "Creative Director",
    "Visual Designer",
    "Brand Designer",
    "Interaction Designer"
  ],
  "Finance, Accounting & Treasury": [
    "Financial Analyst",
    "Senior Financial Analyst",
    "Finance Manager",
    "Director of Finance",
    "VP of Finance",
    "Chief Financial Officer (CFO)",
    "Investment Analyst",
    "Portfolio Manager",
    "Accountant",
    "Senior Accountant",
    "Accounting Manager",
    "Financial Controller",
    "Risk Manager",
    "Treasury Analyst",
    "Tax Manager",
    "Internal Auditor",
    "Billing & Collections Specialist"
  ],
  "Human Resources, Talent & L&D": [
    "HR Generalist",
    "HR Manager",
    "Director of Human Resources",
    "Chief People Officer",
    "Talent Acquisition Specialist",
    "Recruiter",
    "Senior Recruiter",
    "HR Business Partner (HRBP)",
    "Compensation & Benefits Specialist",
    "L&D Coordinator",
    "Learning & Development Specialist",
    "Learning & Development Manager",
    "Director of Learning & Development",
    "Instructional Designer",
    "Head of L&D and Enablement",
    "HR Operations Specialist",
    "People Analytics Specialist",
    "Diversity, Equity & Inclusion (DEI) Lead"
  ],
  "Sales, Partnerships & Account Management": [
    "Account Executive",
    "Senior Account Executive",
    "Sales Manager",
    "Director of Sales",
    "VP of Sales",
    "Business Development Rep (BDR)",
    "Sales Development Rep (SDR)",
    "Account Manager",
    "Key Account Manager",
    "Customer Success Manager",
    "Head of Sales",
    "Enterprise Director",
    "Channel Partnerships Manager",
    "Commercial Director"
  ],
  "Marketing, Growth & Communications": [
    "Marketing Coordinator",
    "Marketing Specialist",
    "Digital Marketing Manager",
    "Growth Marketer",
    "Director of Marketing",
    "Chief Marketing Officer (CMO)",
    "Content Strategist",
    "SEO Specialist",
    "Social Media Manager",
    "Product Marketing Manager",
    "Brand Manager",
    "PR & Communications Lead",
    "Event Coordinator",
    "Email Marketing Specialist",
    "Copywriter"
  ],
  "Operations, Logistics & Supply Chain": [
    "Operations Associate",
    "Operations Manager",
    "Director of Operations",
    "Chief Operating Officer (COO)",
    "Supply Chain Analyst",
    "Logistics Manager",
    "Procurement Specialist",
    "Project Manager",
    "Program Manager",
    "Scrum Master",
    "Inventory Control Planner",
    "Facilities Manager",
    "Fleet Administrator"
  ],
  "Legal, Risk, Regulatory & Compliance": [
    "Legal Counsel",
    "Senior Counsel",
    "General Counsel",
    "Compliance Officer",
    "Contract Administrator",
    "Paralegal",
    "Data Privacy Officer",
    "Regulatory Affairs Specialist",
    "Risk Analyst",
    "Corporate Secretary"
  ],
  "Information Security & Cybersecurity": [
    "Information Security Analyst",
    "Security Engineer",
    "Penetration Tester (Ethical Hacker)",
    "Identity & Access Management (IAM) Engineer",
    "SecOps Manager",
    "Chief Information Security Officer (CISO)",
    "Security Architect",
    "GRC (Governance, Risk & Compliance) Analyst"
  ],
  "Customer Success, Support & Ops": [
    "Customer Support Agent",
    "Technical Support Engineer",
    "Customer Success Representative",
    "Customer Success Team Lead",
    "Customer Support Manager",
    "Director of Customer Experience (CX)",
    "Implementation Specialist",
    "Support Operations Analyst"
  ],
  "Business Strategy, Corporate Dev & VC": [
    "Strategy Associate",
    "Strategy Manager",
    "Corporate Development Analyst",
    "Director of Corporate Development",
    "Chief of Staff",
    "Business Analyst",
    "Venture Capital Associate",
    "Investment Director"
  ],
  "Healthcare, Medicine & Biotech": [
    "Medical Director",
    "Principal Scientist",
    "Research Assistant",
    "Clinical Research Associate",
    "Biomedical Engineer",
    "Lab Manager",
    "Bioinformatics Analyst",
    "Medical Science Liaison (MSL)"
  ]
};

export const TITLE_DEFAULT_ROLES: Record<string, string> = {
  // Engineering & Technology
  "Software Engineer": "Develop and maintain core application modules, write clean frontend/backend code, and write automated tests.",
  "Senior Software Engineer": "Responsible for designing system modules, guiding juniors, writing scalable complex services, and system refactoring.",
  "Lead Software Engineer": "Technical leadership, system design, and managing a team of engineers on microservices architecture.",
  "Staff Software Engineer": "Architecting company-wide platforms, evaluating tech stacks, technical strategy, and unblocking engineering teams.",
  "Engineering Manager": "Managing teams of engineers, sprint planning, tracking SLAs, mentorship, recruitment, and delivery of products.",
  "Director of Engineering": "Leading a multi-team engineering department, budget allocation, technical vision, and executive alignment.",
  "VP of Engineering": "Overseeing entire engineering organization, high-level structural strategy, corporate engineering policy, and talent growth.",
  "Chief Technology Officer (CTO)": "Executive design of entire technical landscape, choosing fundamental frameworks, managing security, and presenting to board.",
  "DevOps Engineer": "Configuring CI/CD pipelines, container orchestration (Kubernetes), Dockerizing workflows, and managing server clusters.",
  "Cloud Architect": "Designing scalable public and private cloud fabrics, security controls, and resource utilization strategies.",
  "Frontend Developer": "Translating Figma designs into pixel-perfect responsive web templates using modern JS frameworks.",
  "Backend Developer": "Constructing robust server microservices, query tuning, RESTful APIs, and transaction processing.",
  "Fullstack Developer": "End-to-end feature delivery, handling state management in React and routing in backend nodes.",
  "QA Automation Engineer": "Writing end-to-end integration test suites utilizing tools like Playwright, Cypress, or Selenium.",
  "Solutions Architect": "Mapping technical systems directly to partner integration capabilities and building client integration prototypes.",
  "Reliability Engineer (SRE)": "Maximizing server uptimes, continuous application monitoring, logging analysis, and handling on-call incidents.",
  "Systems Engineer": "Modeling and managing complex physical/virtual systems, hardware interfaces, and physical infrastructure configuration.",
  "Firmware Engineer": "Developing low-level software instructions targeting memory and microprocessor chips embedded on proprietary hardware boards.",
  "Mobile App Developer (iOS/Android)": "Developing and performance-optimizing fluid native interfaces for iOS and Android environments.",
  "Technical Program Manager (TPM)": "Translating complex product requirements into explicit milestone dependency gantts and managing high-stakes launch logistics.",

  // Data Science, Analytics & AI
  "Data Scientist": "Developing machine learning regression/classification models, cleaning dense datasets, and data storytelling.",
  "Senior Data Scientist": "Devising custom training pipelines, deploying deep neural nets, and translating complex math into client value.",
  "Machine Learning Engineer": "Scaling model inference systems, configuring GPU clusters, and fine-tuning open-weight LLMs.",
  "AI Researcher": "Prototyping academic algorithm breakthroughs and evaluating custom attention variants for model training.",
  "NLP Specialist": "Engineering tokenization, vocabulary maps, sequence-to-sequence converters, and parsing semantic nuances in textual datasets.",
  "Computer Vision Engineer": "Implementing image segmentations, bounding boxes, feature tracking filters, and convolution layers on visual databases.",
  "Data Analyst": "Querying SQL servers, preparing high-fidelity dashboards inside Tableau, and generating business intelligence briefings.",
  "Data Engineer": "Designing solid ETL/ELT pipelines, managing Snowflake or Redshift data lakes, and optimizing data schemas.",
  "Senior Data Engineer": "Architecting real-time streaming pipelines (Kafka, Flink) and keeping petabyte-scale datastores cost-efficient.",
  "Director of AI/ML": "Formulating complete corporate AI strategies, deploying models to production safely, and setting research priorities.",
  "BI Analyst (Business Intelligence)": "Structuring complex analytical reports, optimizing views, and conducting business metric audits.",
  "Analytics Manager": "Handling analysts, choosing metric frameworks, and presenting key operational performance indicators to management.",
  "Database Administrator (DBA)": "Grooming database indices, tuning high-latency queries, planning structural backups, and scheduling security updates.",
  "MLOps Engineer": "Developing robust automated model monitoring grids to detect data drifts, validation failures, and model prediction skews.",

  // Product, UI/UX & Design
  "Associate Product Manager": "Drafting granular feature requirements (PRDs), coordinating engineering design sprints, and analyzing user metrics.",
  "Product Manager": "Guiding cross-functional teams, prioritizing roadmap backlogs, and launching successful digital features.",
  "Senior Product Manager": "Directing core multi-quarter product strategies, managing complex integrations, and defining success KPIs.",
  "Director of Product": "Directing entire families of products, aligning portfolios, managing resource pools, and guiding PM talent.",
  "VP of Product": "Orchestrating long-term product vision, collaborating on corporate strategy, and growing high-velocity product teams.",
  "Product Owner": "Translating PM vision into detailed backlog issues, clarifying requirements, and hosting daily sprint standups.",
  "UI/UX Designer": "Prototyping fluid user interfaces, building interactive user testing layouts, and maintaining component design libraries.",
  "Senior Product Designer": "Unifying web, mobile, and system design philosophies, auditing user experiences, and mentoring designer teams.",
  "UX Researcher": "Conducting comprehensive interviews, preparing screen recordings, and cataloging user pain points.",
  "Design Manager": "Supervising teams of designers, defining visual style constraints, and ensuring high-quality aesthetics.",
  "Creative Director": "Directing whole corporate branding templates, defining company aesthetics, and formatting key campaign visuals.",
  "Visual Designer": "Crafting premium corporate graphics, micro-illustrations, pitch layouts, and promotional media files.",
  "Brand Designer": "Forming unified design guidelines, color codes, typographic standards, and visual layout guides.",
  "Interaction Designer": "Constructing visual feedback animations, state transitions, interactive mockups, and micro-interaction models.",

  // Finance, Accounting & Treasury
  "Financial Analyst": "Developing complex financial forecast models, conducting margin analyses, and preparing annual budget spreadsheets.",
  "Senior Financial Analyst": "Auditing division level revenues, running variance analyses, and offering strategic fiscal recommendations.",
  "Finance Manager": "Handling accounting ledger alignment, supervising analysts, and conducting monthly corporate closing tasks.",
  "Director of Finance": "Overseeing capital allocation projects, evaluating fiscal health metrics, and presenting quarterly reports.",
  "VP of Finance": "Handling high-level capitalization plans, corporate assets, treasury controls, and managing multi-region audits.",
  "Chief Financial Officer (CFO)": "Directing corporate fiscal roadmap, presenting performance indices to investors, and guiding large capital transfers.",
  "Investment Analyst": "Evaluating market opportunities, constructing dense capitalization models, and writing deal investment memos.",
  "Portfolio Manager": "Reviewing diverse asset allocations, managing risk premiums, and executing strategic financial trades.",
  "Accountant": "Reconciling daily banking transactions, filing commercial taxation documents, and preparing general ledgers.",
  "Senior Accountant": "Handling critical complex payroll computations, processing tax inquiries, and aligning financial records.",
  "Accounting Manager": "Supervising bookkeepers, certifying audit readiness, and compiling accurate end-of-year accounts.",
  "Financial Controller": "Managing corporate ledger structures, checking internal regulatory policy compliance, and auditing expense items.",
  "Risk Manager": "Auditing high-level corporate vulnerabilities, checking regulatory rules, and designing mitigation guidelines.",
  "Treasury Analyst": "Optimizing banking liquidities, tracking exchange rate fluctuations, and managing debt structures.",
  "Tax Manager": "Assessing commercial tax exposures, preparing transfer pricing reviews, and checking local and international tax laws.",
  "Internal Auditor": "Inspecting financial data processing workflows and assessing operational efficiency metrics across accounting lines.",
  "Billing & Collections Specialist": "Managing account invoice deliveries, auditing payment records, and contacting overdue accounts.",

  // Human Resources, Talent & L&D
  "HR Generalist": "Answering simple employee inquires, preparing employment contracts, and tracking leave balances.",
  "HR Manager": "Handling staff relation issues, updating regulatory guidelines, and supervising administrative personnel.",
  "Director of Human Resources": "Strategizing talent acquisition, global employee engagement, compliance, and managing HR teams.",
  "Chief People Officer": "Aesthetic design of corporate culture parameters, shaping retention plans, and setting workplace guidelines.",
  "Talent Acquisition Specialist": "Sourcing qualified candidates, organizing preliminary phone screenings, and hosting panels.",
  "Recruiter": "Coordinating external candidate searches, managing applicant tracking software, and formatting offers.",
  "Senior Recruiter": "Conducting critical senior-level executive searches, salary negotiations, and designing employer brand assets.",
  "HR Business Partner (HRBP)": "Aligning department managers around strategic workforce development plans and handling disputes.",
  "Compensation & Benefits Specialist": "Benchmarking industry salary reviews, analyzing local tax adjustments, and managing medical schemes.",
  "L&D Coordinator": "Scheduling corporate training sprints, coordinating guest speakers, and managing learning platform logins.",
  "Learning & Development Specialist": "Designing specific talent development programs, administering skills-gap analyses, and evaluating training paths.",
  "Learning & Development Manager": "Orchestrating company-wide education programs, allocating training budgets, and checking execution rates.",
  "Director of Learning & Development": "Defining global skill acquisition models, building leadership development projects, and aligning educational budgets.",
  "Instructional Designer": "Authoring interactive technical training curricula, storyboarding digital learning guides, and assembling asset packets.",
  "Head of L&D and Enablement": "Directing complete corporate personnel education strategies, measuring performance uplifts, and buying enterprise tools.",
  "HR Operations Specialist": "Configuring HR database systems, managing employee records, and automating standardized onboarding forms.",
  "People Analytics Specialist": "Constructing predictive turnover dashboards, checking hiring metrics, and evaluating compensation equities.",
  "Diversity, Equity & Inclusion (DEI) Lead": "Designing inclusive workspace development blueprints, coordinating affinity events, and hosting equity reviews.",

  // Sales, Partnerships & Account Management
  "Account Executive": "Hosting customized product walkthroughs, addressing procurement inquiries, and closing contract deals.",
  "Senior Account Executive": "Managing complex enterprise customer pipelines, negotiating pricing limits, and ensuring multi-year renewals.",
  "Sales Manager": "Coordinating individual sales targets, designing custom training guides, and tracking sales quotas.",
  "Director of Sales": "Expanding regional market shares, managing multi-tier sales channels, and orchestrating enterprise contracts.",
  "VP of Sales": "Directing world-wide sales strategies, setting global quarterly targets, and structuring commissions.",
  "Business Development Rep (BDR)": "Initiating outbound contact cold leads, formatting customized value propositions, and booking demo sessions.",
  "Sales Development Rep (SDR)": "Processing incoming leads rapidly, answering primary product inquiries, and qualifying corporate leads.",
  "Account Manager": "Supervising client accounts, identifying cross-selling routes, and addressing client requirements.",
  "Key Account Manager": "Nurturing relationships with top corporate accounts, designing custom solution maps, and ensuring renewals.",
  "Customer Success Manager": "Assisting new users onboarding, tracking product adoption rates, and presenting user value reviews.",
  "Head of Sales": "Formulating comprehensive distribution strategies, managing international agencies, and aligning scaling initiatives.",
  "Enterprise Director": "Overseeing strategic high-value enterprise accounts, leading sales pods, and negotiating top-tier deals.",
  "Channel Partnerships Manager": "Managing partner relationships, running co-marketing programs, and expanding active distribution channels.",
  "Commercial Director": "Setting unified commercial margins, analyzing commercial contract risks, and steering growth.",

  // Marketing, Growth & Communications
  "Marketing Coordinator": "Formatting visual assets, updating website content lists, and tracking marketing campaigns.",
  "Marketing Specialist": "Designing specific target ad campaigns, conducting user surveys, and reporting ROI data.",
  "Digital Marketing Manager": "Optimizing paid search campaigns, managing ad budgets, and adjusting conversion funnels.",
  "Growth Marketer": "A/B testing sign-up procedures, building viral loops, and optimizing product activation rates.",
  "Director of Marketing": "Directing entire corporate marketing programs, planning major launch campaigns, and auditing brand consistency.",
  "Chief Marketing Officer (CMO)": "Formatting absolute brand positioning strategies, allocating media spend grids, and coordinating large agencies.",
  "Content Strategist": "Developing cohesive publication plans, outlining blog series, and ensuring corporate tone-of-voice alignment.",
  "SEO Specialist": "Analyzing keyword gaps, designing backlink strategies, and auditing technical search crawl indicators.",
  "Social Media Manager": "Creating engaging digital update posts, monitoring online brand discussions, and hosting web discussions.",
  "Product Marketing Manager": "Designing clear feature positioning frameworks, drafting sales collateral, and coordinating launch material.",
  "Brand Manager": "Reviewing brand recognition metrics, compiling design assets, and verifying logo applications.",
  "PR & Communications Lead": "Managing media relations, reviewing press documentation, and coordinating active corporate communications panels.",
  "Event Coordinator": "Managing corporate trade show presences, booking venues, and formatting event attendee materials.",
  "Email Marketing Specialist": "Assembling outbound mail templates, analyzing drop-offs, mapping target subscriber groups, and setting up triggers.",
  "Copywriter": "Drafting core corporate call-to-actions, headline copy, promotional lines, and editing informational scripts.",

  // Operations, Logistics & Supply Chain
  "Operations Associate": "Assisting on standard system processes, tracking metrics, and preparing data spreadsheets.",
  "Operations Manager": "Optimizing company day-to-day operations, streamlining communication, and managing facility budgets.",
  "Director of Operations": "Spearheading multi-office operational expansions, reviewing cost ratios, and coordinating scaling plans.",
  "Chief Operating Officer (COO)": "Executive alignment of operational divisions, overseeing delivery, and reviewing operational performance indices.",
  "Supply Chain Analyst": "Tracking manufacturer lead times, reviewing cost structures, and designing lean supply procedures.",
  "Logistics Manager": "Coordinating physical carrier schedules, planning warehouse layouts, and managing shipping budgets.",
  "Procurement Specialist": "Filing request-for-proposals (RFPs), analyzing vendor criteria bid documents, and negotiating trade terms.",
  "Project Manager": "Creating detailed project schedules, monitoring milestones, and unblocking project dependencies.",
  "Program Manager": "Coordinating groups of related projects, allocating core resources, and tracking high-level performance.",
  "Scrum Master": "Hosting agile methodology rituals, unblocking sprint tasks, and coaching teams on self-organization.",
  "Inventory Control Planner": "Auditing storage cycles, forecasting raw materials run rates, and preventing resource shortages.",
  "Facilities Manager": "Overseeing physical buildings maintenance, planning office seating layouts, and managing security panels.",
  "Fleet Administrator": "Tracking mobile fleet locations, managing fuel cards, and coordinating diagnostic repair inspections.",

  // Legal, Risk, Regulatory & Compliance
  "Legal Counsel": "Drafting commercial services agreements, reviewing client NDAs, and answering litigation queries.",
  "Senior Counsel": "Negotiating enterprise acquisition terms, identifying regulatory liabilities, and representing corporate interest.",
  "General Counsel": "Guiding corporate board of directors on safe growth routes and managing external litigation councils.",
  "Compliance Officer": "Auditing internal compliance procedures, training personnel, and resolving regulatory updates.",
  "Contract Administrator": "Cataloging active corporate service contracts and tracking expiry dates.",
  "Paralegal": "Assembling court case documents, scanning statutory codes, and compiling legal briefs.",
  "Data Privacy Officer": "Auditing product compliance with GDPR/CCPA frameworks and managing user data deletion requests.",
  "Regulatory Affairs Specialist": "Drafting deep application dossier folders for submission to the FDA or EMA health boards.",
  "Risk Analyst": "Calculating corporate credit risks, tracking vendor liabilities, and outlining exposure ratios.",
  "Corporate Secretary": "Documenting corporate board meetings, preparing governance materials, and certifying standard stock records.",

  // Information Security & Cybersecurity
  "Information Security Analyst": "Monitoring network traffic, identifying intrusion attempts, and patching vulnerabilities.",
  "Security Engineer": "Constructing security controls, identity verification firewalls, and data encryption grids.",
  "Penetration Tester (Ethical Hacker)": "Conducting deliberate security breaches to identify security system exploits and formatting reports.",
  "Identity & Access Management (IAM) Engineer": "Setting up single sign-on parameters, directory groups, and multi-factor credentials.",
  "SecOps Manager": "Managing incident recovery pipelines, running table-top simulations, and certifying threat dashboards.",
  "Chief Information Security Officer (CISO)": "Setting standard identity protection schemas and presenting security postures to corporate stakeholders.",
  "Security Architect": "Drafting core network maps, security policy rules, and evaluating cloud isolation models.",
  "GRC (Governance, Risk & Compliance) Analyst": "Mapping technology operations directly targeting ISO 27001, SOC2, or HIPAA compliance structures.",

  // Customer Success, Support & Ops
  "Customer Support Agent": "Responding to incoming user requests, resolving simple issues, and filing detailed bugs.",
  "Technical Support Engineer": "Digging into server log dumps, verifying database records, and troubleshooting intricate technical bugs.",
  "Customer Success Representative": "Leading initial client product onboarding, driving product engagement, and verifying user satisfaction.",
  "Customer Success Team Lead": "Grooming standard response times, analyzing review scores, and resolving escalated client complaints.",
  "Customer Support Manager": "Supervising customer support pipelines, scheduling shifts, and tracking user satisfaction targets.",
  "Director of Customer Experience (CX)": "Designing end-to-end customer journey maps, purchasing ticketing suites, and adjusting SLAs.",
  "Implementation Specialist": "Configuring customized corporate client databases and running training webinars.",
  "Support Operations Analyst": "Developing performance reports, auditing ticket tagging patterns, and choosing support tools.",

  // Business Strategy, Corporate Dev & VC
  "Strategy Associate": "Constructing competitor intelligence dashboards and forecasting long-range economic trends.",
  "Strategy Manager": "Sizing market adjacencies, highlighting integration routes, and coordinating executive policy forums.",
  "Corporate Development Analyst": "Developing strategic M&A valuation sheets, modeling synergies, and summarizing prospects.",
  "Director of Corporate Development": "Directing complex target acquisition pipelines and managing active joint venture plans.",
  "Chief of Staff": "Unifying executive focus priorities, drafting boardroom briefings, and tracking strategic milestones.",
  "Business Analyst": "Defining precise operational process steps, mapping workflows, and gathering system requirements.",
  "Venture Capital Associate": "Reviewing pitch decks, preparing market overviews, and analyzing investment parameters.",
  "Investment Director": "Evaluating long-term capitalization strategies and negotiating investment packages.",

  // Healthcare, Medicine & Biotech
  "Medical Director": "Providing expert clinical oversight, designing security protocols, and managing medical teams.",
  "Principal Scientist": "Drafting clinical test hypotheses, reviewing complex molecule models, and supervising lab activities.",
  "Research Assistant": "Running laboratory test checks, cataloging findings, and setting up equipment arrays.",
  "Clinical Research Associate": "Monitoring regional clinical test trials and ensuring safety metrics are fully adhered to.",
  "Biomedical Engineer": "Configuring technical healthcare equipment and testing custom diagnostics software engines.",
  "Lab Manager": "Managing inventory of critical supplies and verifying safety equipment compliance.",
  "Bioinformatics Analyst": "Modeling complex genomic sequence alignments to trace mutation clusters.",
  "Medical Science Liaison (MSL)": "Educating regional healthcare providers regarding clinical drug metrics and safety guides."
};
